### ISSUE TITLE
미니캘린더에 일정 띄우기

### ISSUE THREAD

**Issue by jinyowo** [jinyowo/NTSCalendar#157]
반복일정의 경우에는 첫 이벤트만 일정을 띄웁니다.

**Comment by jinyowo** [comment]
이벤트가 포함되는 날에 td에 mini-event클래스를 추가하면됩니다.
현재 td에 data-date속성으로 메인캘린더와 똑같이 2017-01-01형태로 날짜가 저장되어있습니다

**Comment by kameru** [comment]
브랜치는 같은 브랜치 사용하면 되나요?
