### ISSUE TITLE
more...옆에 마우스 모양은 변하는데 클릭은 안되요

### ISSUE THREAD

**Issue by jinyowo** [jinyowo/NTSCalendar#166]
more...옆에 빈공간에 마우스를 올리면 마우스 모양은 바뀌어서 
클릭하면 이벤트를 생성할 수 있는거같지만 실제로 클릭은 안되네요 

마우스모양을 바꾸지말던가 클릭이 되게하던가 둘 중 하나로 바꾸면 좋겠어요

**Comment by kameru** [comment]
해당 부분을 .fc-more-cell이 차지하고 있어서 생기는 문제인 것 같습니다.
