### ISSUE TITLE
달력 출력을 display 처리 후에 해주세요.

### ISSUE THREAD

**Issue by kameru** [jinyowo/NTSCalendar#51]
현재 week -> month로 변경하면 일정이 잘못 나오는 문제 때문에 month-calendar에서 일정을 세팅 하였더니 주간 달력과 일간 달력의 element를 가져와서 오류가 납니다.
가능하다면 display 이후에 달력 출력 함수를 불러와주셨으면 합니다.

**Comment by jinyowo** [comment]
<img width="589" alt="2017-01-24 10 12 05" src="https://cloud.githubusercontent.com/assets/11749756/22229864/a5b8b02c-e21d-11e6-9480-0900c6de8282.png">
이 오류가 맞나요??  
display먼저 설정하고 달력을 그렸는데도 계속 오류가 납니다

**Comment by kameru** [comment]
이벤트에 resetEvent()를 안넣어서 생긴 문제였네요...수정하고 푸시하겠습니다

**Comment by jinyowo** [comment]
issue close할게요~
